# Makefile to build all the examples/tests using my c compiler
# By Eudis Duran


EXECS = bin/ex1.vm bin/ex2.vm bin/ex3.vm bin/ex4.vm bin/ex5.vm bin/ex6.vm bin/ex7.vm 

$(EXECS) : $(EXECS)

bin/ex1.vm: src/ex1.c
	bin/c src/ex1.c -o bin/ex1.vm

bin/ex2.vm: src/ex2.c
	bin/c src/ex2.c -o bin/ex2.vm

bin/ex3.vm: src/ex3.c
	bin/c src/ex3.c -o bin/ex3.vm

bin/ex4.vm: src/ex4.c
	bin/c src/ex4.c -o bin/ex4.vm

bin/ex5.vm: src/ex5.c
	bin/c src/ex5.c -o bin/ex5.vm

bin/ex6.vm: src/ex6.c
	bin/c src/ex6.c -o bin/ex6.vm

bin/ex7.vm: src/ex7.c
	bin/c src/ex7.c -o bin/ex7.vm


